// fix42_order_encoder.cpp
#include <iostream>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>
#include <cstdint>

namespace fix42 {

constexpr char SOH = '\x01';

/// 计算字符串所有字节之和（无符号） mod 256
static int checksum(const std::string& data) {
    uint32_t sum = 0;
        for (unsigned char ch : data) sum += ch;
            return sum % 256;
            }

            /// 用于构造并编码一个 New Order Single 消息
            class NewOrderSingleBuilder {
            public:
                // === Header 字段 ===
                    std::string beginString = "FIX.4.2";      // 8
                        std::string senderCompID;                 // 49
                            std::string targetCompID;                 // 56
                                std::string onBehalfOfCompID;             // 115 (可空)
                                    uint32_t    msgSeqNum = 1;                // 34
                                        std::string sendingTime;                  // 52 (yyyyMMdd-HH:mm:ss[.sss])

                                            // === Body 字段 ===
                                                std::string clOrdID;          // 11
                                                    char        handlInst = '1';  // 21  (1=自动执行, 2=自动, 3=手动)
                                                        std::string symbol;           // 55
                                                            char        side = '1';       // 54  (1=Buy, 2=Sell …)
                                                                std::string transactTime;     // 60
                                                                    char        ordType = '2';    // 40  (1=市价, 2=限价 …)
                                                                        std::string clientID;         // 109
                                                                            double      orderQty = 0;     // 38
                                                                                double      price = 0;        // 44
                                                                                    std::string securityExchange; // 207
                                                                                        std::string account;          // 1

                                                                                            /// 生成最终 FIX 消息字符串
                                                                                                std::string build() const {
                                                                                                        std::ostringstream oss;

                                                                                                                // -------- Header（先放占位的 8、9，9 之后补） --------
                                                                                                                        oss << "8="  << beginString << SOH;
                                                                                                                                oss << "9="  << "0000"      << SOH;           // 4 位占位，稍后替换
                                                                                                                                        oss << "35=" << 'D'         << SOH;           // MsgType = D (NewOrderSingle)
                                                                                                                                                oss << "49=" << senderCompID      << SOH;
                                                                                                                                                        oss << "56=" << targetCompID      << SOH;
                                                                                                                                                                if (!onBehalfOfCompID.empty())
                                                                                                                                                                            oss << "115=" << onBehalfOfCompID << SOH;
                                                                                                                                                                                    oss << "34=" << msgSeqNum          << SOH;
                                                                                                                                                                                            oss << "52=" << sendingTime        << SOH;

                                                                                                                                                                                                    // -------- Body --------
                                                                                                                                                                                                            oss << "11="  << clOrdID           << SOH;
                                                                                                                                                                                                                    oss << "21="  << handlInst         << SOH;
                                                                                                                                                                                                                            oss << "55="  << symbol            << SOH;
                                                                                                                                                                                                                                    oss << "54="  << side              << SOH;
                                                                                                                                                                                                                                            oss << "60="  << transactTime      << SOH;
                                                                                                                                                                                                                                                    oss << "40="  << ordType           << SOH;
                                                                                                                                                                                                                                                            oss << "109=" << clientID          << SOH;
                                                                                                                                                                                                                                                                    oss << "38="  << orderQty          << SOH;
                                                                                                                                                                                                                                                                            oss << "44="  << price             << SOH;
                                                                                                                                                                                                                                                                                    oss << "207=" << securityExchange  << SOH;
                                                                                                                                                                                                                                                                                            oss << "1="   << account           << SOH;

                                                                                                                                                                                                                                                                                                    // -------- Trailer: 先把头尾之外的内容抓出来算 9=BodyLength --------
                                                                                                                                                                                                                                                                                                            std::string bodyAndHeaderExcept8and9 = oss.str().substr(
                                                                                                                                                                                                                                                                                                                        /*pos=*/ std::string("8=" + beginString + std::string(1, SOH) + "9=0000" + std::string(1, SOH)).size());

                                                                                                                                                                                                                                                                                                                                std::size_t bodyLength = bodyAndHeaderExcept8and9.size();   // 字节数
                                                                                                                                                                                                                                                                                                                                        // 填回真正的 9=BodyLength
                                                                                                                                                                                                                                                                                                                                                std::ostringstream oss2;
                                                                                                                                                                                                                                                                                                                                                        oss2 << "8=" << beginString << SOH
                                                                                                                                                                                                                                                                                                                                                                     << "9=" << bodyLength  << SOH
                                                                                                                                                                                                                                                                                                                                                                                  << bodyAndHeaderExcept8and9;

                                                                                                                                                                                                                                                                                                                                                                                          // -------- CheckSum --------
                                                                                                                                                                                                                                                                                                                                                                                                  int csum = checksum(oss2.str());
                                                                                                                                                                                                                                                                                                                                                                                                          oss2 << "10=" << std::setw(3) << std::setfill('0') << csum << SOH;

                                                                                                                                                                                                                                                                                                                                                                                                                  return oss2.str();
                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                      } // namespace fix42

                                                                                                                                                                                                                                                                                                                                                                                                                      // ---------------- 示例 ----------------
                                                                                                                                                                                                                                                                                                                                                                                                                      int main() {
                                                                                                                                                                                                                                                                                                                                                                                                                          fix42::NewOrderSingleBuilder builder;
                                                                                                                                                                                                                                                                                                                                                                                                                              // ========== Header ==========
                                                                                                                                                                                                                                                                                                                                                                                                                                  builder.senderCompID      = "BROKER12";
                                                                                                                                                                                                                                                                                                                                                                                                                                      builder.targetCompID      = "EXCHANGE";
                                                                                                                                                                                                                                                                                                                                                                                                                                          builder.onBehalfOfCompID  = "CLIENTA";
                                                                                                                                                                                                                                                                                                                                                                                                                                              builder.msgSeqNum         = 15;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  builder.sendingTime       = "20250714-11:20:45.123";

                                                                                                                                                                                                                                                                                                                                                                                                                                                      // ========== Body ==========
                                                                                                                                                                                                                                                                                                                                                                                                                                                          builder.clOrdID           = "ORDER-20250714-001";
                                                                                                                                                                                                                                                                                                                                                                                                                                                              builder.handlInst         = '1';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  builder.symbol            = "AAPL";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      builder.side              = '1';                 // 买
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          builder.transactTime      = "20250714-11:20:45.123";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              builder.ordType           = '2';                 // 限价
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  builder.clientID          = "C789";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      builder.orderQty          = 100;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          builder.price             = 215.5;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              builder.securityExchange  = "XNAS";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  builder.account           = "ACC-445566";

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      std::string fixMsg = builder.build();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          std::cout << "Encoded FIX 4.2 message:\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 为了可视化，把 SOH 打印成 '|'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for (char ch : fixMsg) std::cout << (ch == fix42::SOH ? '|' : ch);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      std::cout << '\n';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }